### ISSUE TITLE
Mosh

### ISSUE THREAD

**Issue by erdnaxeli** [irssiconnectbot/irssiconnectbot2#1]
Please add mosh support. JuicesSSH has it, but miss all the amazing features of irssi connectbot.

**Comment by matiasw** [comment]
Have a look at https://dan.drown.org/android/mosh/

**Comment by erdnaxeli** [comment]
Yeah, in 8 years I had time to find out about this one :smile: 

Actually I don't even use irssiconnectbot anymore.
